### ISSUE TITLE
Indentation issue in this part

### ISSUE THREAD

**Issue by rczheng** [staoxiao/LibVQ#1]
https://github.com/staoxiao/LibVQ/blob/335fc5d5e9ee3c17d45aca2dcd855e16552e8c81/examples/MSMARCO/learnable_index/train_index.py#L115

There might exist Indentation issue in this line. The code will never go into this part. And if training_mode="distill_index_nolabel", the error will raise because there is no train-virtual_rel.tsv.

**Comment by staoxiao** [comment]
This error has been fixed. Thanks!
