### ISSUE TITLE
How to eval datasets?

### ISSUE THREAD

**Issue by zhanghan9797** [staoxiao/LibVQ#2]
How to compute results after training if i get 'rotate_matrix', 'codebook' and 'ivf_centers'?
Can you give me a reference for this part of the code?

**Comment by staoxiao** [comment]
After training, the LearnableIndex will automatically select the latest checkpoint to update the index, and you can test the performance by following our [examples](https://github.com/staoxiao/LibVQ/blob/master/examples/MSMARCO/learnable_index/train_index.py). If you want to specify a checkpoint, please refer to following commands:
1. update the encoder by index.[update_encoder(ckpt_file)](https://github.com/staoxiao/LibVQ/blob/master/LibVQ/learnable_index/learnable_index_with_encoder.py) if you train the encoder. And inference the new embeddings.
1. update the index by index.[update_index_with_ckpt(ckpt_file, doc_embeddings)](https://github.com/staoxiao/LibVQ/blob/master/LibVQ/learnable_index/learnable_index.py)
4. ANN search with the new index: index.search(query_embeddings)

**Comment by zhanghan9797** [comment]
Hi,
First, i init a ivf index like this:
```
quantizer = faiss.IndexFlatIP(emb_size)
index = faiss.IndexIVFFlat(quantizer, emb_size, ivf_centers_num, faiss.METRIC_INNER_PRODUCT)
```
Then, I update IndexIVFFlat's centers like this:
```
coarse_quantizer = faiss.downcast_index(index.quantizer)  
faiss.copy_array_to_vector(center_vecs.ravel(),coarse_quantizer.xb)
```
After that,i want to add corpus to this index and search, however this error occur:
```
terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in faiss::IndexIVF::search_preassigned(faiss::Index::idx_t, const float*, faiss::Index::idx_t, const idx_t*, const float*, float*, faiss::Index::idx_t*, bool, const faiss::IVFSearchParameters*, faiss::IndexIVFStats*) const::<lambda(faiss::Index::idx_t, float, float*, faiss::Index::idx_t*)> at /project/faiss/faiss/IndexIVF.cpp:469: Error: 'key < (idx_t)nlist' failed: Invalid key=140461314990592 nlist=10000
```

**Comment by staoxiao** [comment]
Sorry for the late reply. Could you provide the detailed pipeline, especially the code for adding and searching?

**Comment by zhanghan9797** [comment]
Sorry i just saw the message. I re-describe my code：
Firstly, i init my index like this:
```
quantizer = faiss.IndexFlatIP(768)
index = faiss.IndexIVFFlat(quantizer, emb_size, 10000, faiss.METRIC_INNER_PRODUCT)
```
Secondly，i want to update ivf centers by myself like  [update_ivf](https://github.com/staoxiao/LibVQ/blob/master/LibVQ/learnable_index/learnable_index.py).
Thirdly, i add and search like this:
```
index.is_trained = True
index.add(doc_embeddings)
_, dev_I = index.search(query_embeddings, topN)
```
Finally, the error like this:
```
terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in faiss::IndexIVF::search_preassigned(faiss::Index::idx_t, const float*, faiss::Index::idx_t, const idx_t*, const float*, float*, faiss::Index::idx_t*, bool, const faiss::IVFSearchParameters*, faiss::IndexIVFStats*) const::<lambda(faiss::Index::idx_t, float, float*, faiss::Index::idx_t*)> at /project/faiss/faiss/IndexIVF.cpp:469: Error: 'key < (idx_t)nlist' failed: Invalid key=140632705020480 nlist=10000
```
I guess it is not allowed to re-add doc_embeddings with an untrained index.

**Comment by zhanghan9797** [comment]
Hi, I found a solution to this error，when update_ivf we should operate like this:
```
index.quantizer.reset()
index.quantizer.add(center_vecs)
```
This is a high level way of accessing the centroids and here is my [reference](https://github.com/facebookresearch/faiss/issues/2341).

**Comment by staoxiao** [comment]
Thank you for the high-level way! I will consider to update the repo to make it easier to use.
