### ISSUE TITLE
some questions about learnable parameters in Distill-VQ

### ISSUE THREAD

**Issue by RuixiangZhao** [staoxiao/LibVQ#5]
Hi, shitao, much thanks for your nice paper `Distill-VQ` and the well-organized open-resourced codebase.

I have some questions about learnable parameters in Distll-VQ after reading your paper:

+ In section 3.2, you mentioned `The above optimization problem involves two groups of learnable parameters: the IVFPQ related parameters **O** and **C**, and the query encoder`. However, the hard assignment in `Eq.2` and `Eq.3` is not differentiable. How to update IVFPQ related parameters **O** and **C** during training?

Looking forward to your reply.

**Comment by staoxiao** [comment]
Thanks for your interest in our work!
Firstly,  we use the nearest center and codewords to calculate the student score in the optimization object, so the **O** and **C** will be updated based on the loss.
Second, we use the straight-through estimator in PQ to make the hard assignment differentiable.  You can refer to the [code](https://github.com/staoxiao/LibVQ/blob/master/LibVQ/models/pq_quantizer.py#L80).
